# For more info on HTTP files go to https://aka.ms/vs/httpfile


POST http://localhost:1337/vendors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklUVVN0dWRlbnQiLCJzdWIiOiJJVFVTdHVkZW50IiwianRpIjoiNWMyZDYyYjgiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1NDgxNyIsImh0dHBzOi8vbG9jYWxob3N0OjAiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciXSwibmJmIjoxNzM4ODc3MzczLCJleHAiOjE3NDY1NjY5NzMsImlhdCI6MTczODg3NzM3NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.5wVKJSaUfqX-Hhm7WUh09U7157OgueYTrGhrUbjdd-M
Content-Type: application/json
{
    "name": "Oracle"
}